### ISSUE TITLE
Callable issue on python 3.10

### ISSUE THREAD

**Issue by AnshumanFauzdar** [edgeimpulse/firmware-sony-spresense#2]
Operating system tested : Windows 10
Python version : 3.10.1

Issue : AttributeError: module "collections" has no attribute "Callable"
![image](https://user-images.githubusercontent.com/40523329/148976546-5129b947-0825-4506-9c9e-85f319479cc2.png)

Fix : replace collections.Callable with collections.abc.Callable [Opened PR #1]

Fix reason : pyreadline/pyreadline#65 (comment)

**Comment by mmajchrzycki** [comment]
Hi @AnshumanFauzdar 
The issue has been fixed in the [latest release](https://github.com/edgeimpulse/firmware-sony-spresense/commit/6b9b56b5d255c99d1f8546109ead2851936ab76d)
