### ISSUE TITLE
Running a Microphone Inference - Hard Fault

### ISSUE THREAD

**Issue by DeveloperMarcial** [edgeimpulse/firmware-sony-spresense#5]
Please close this ticket!
**SOLUTION**: Deploy the `Unoptimized (float32)` and then do a `merge copy`.
---
I am able to download the code, compile it, flash it, run the impulse locally, connect to the _EI Studio_ and upload Samples from the microphone.

* Sony Spresence main board
* Sony Spresence carrier board
* Condenser mic with 2.2k ohm resistor
* Ubuntu 22.04.1 LTS
* Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
* [GCC 7.5.0] :: Anaconda, Inc. on linux
* npm version 8.19.2
* node version v18.10.0
* edge-impulse-daemon version v1.16.0
* Edge Impulse impulse runner v1.16.0

When I drop in my _EI library_ that uses the microphone I get errors. I wasn't sure if I should be using the _Arduino Library_ or the _C++ Library_.

---

### Test Protocol
	
	**Definitions:**
		"3-folders" = 
			`edge-impulse-sdk/`
			`model-parametsrs/`
			`tflite-model`
		"destination folder" = `firmware-sony-spresense-main/edge_impulse/`
		"AC" = EdgeImpulse Arduino C    Library from Impulse Deployment page
		"CC" = EdgeImpulse          C++ Library from Impulse Deployment page

	**Setup:**
		Delete `build` folder in destination folder
		Duplicate destination folder 5 times

	**Test0: Run Accelerometer Model**
		Compile destination folder: 	`make -j`
			Built OK
				`firmware.spk` is successfully created.
		Flash Spresense:				      `make flash`
			Flashed OK
		Connect Spresence to EI Studio:	      `edge-impulse-daemon` 
			Connected OK
			Uploaded a Sample OK
			Sample shows Microphone OK
		Run daemon locally:				`edge-impulse-run-impulse`
			Ran accelerometer inference OK
                        I don't have an accelerometer attached so the inference only ran once.
                              $ edge-impulse-run-impulse
                              Edge Impulse impulse runner v1.16.0
                              [SER] Connecting to /dev/ttyUSB0
                              [SER] Serial is connected, trying to read config...
                              [SER] Retrieved configuration
                              [SER] Device is running AT command version 1.7.0
                              [SER] Started inferencing, press CTRL+C to stop...
                              LSE
                              Inferencing settings:
                                    Interval: 16.0000 ms
                                    Frame size: 375
                                    Sample length: 2000.0000 ms.
                                    No. of classes: 4
                              Starting inferencing, press 'b' to break
                              Sampling...
                              Err: failed to get sensor data **<--EXPECTED**
                              Predictions (DSP: 6 ms., Classification: 0 ms., Anomaly: 0 ms.): 
                                  idle: 	0.996093
                                  snake: 	0.000000
                                  updown: 	0.000000
                                  wave: 	0.000000
                                  anomaly score: -0.066530
                              Starting inferencing in 2 seconds...
                              >                                        **<-- What does one type at this prompt?**

	**Test1: Run Mic Model - Replace 3-folders, Ardy Library** 
		Delete 3-folders in destination folder.
		Copy AC 3-folders to destination folder
		**_make error: undefined reference to `'ei_free(void*)'`_**
			
	**Test2: Run Mic Model - Merge 3-folders, Ardy Library** 
		Copy AC 3-folders to destination folder
		Select `merge folders `when prompted
		Built OK with Warning
			`firmware.spk` is successfully created.
			make: warning:  Clock skew detected.  Your build may be incomplete.
		Flashed OK
		Run daemon locally:				`edge-impulse-run-impulse`
			[SER] Started inferencing, press CTRL+C to stop...
			LSE
			Inferencing settings:
				Interval: 0.0625 ms.
				Frame size: 16000
				Sample length: 1000 ms.
				No. of classes: 4
			Starting inferencing, press 'b' to break
			Recording...
			Recording done
			**_up_hardfault: PANIC!!! Hard fault: 40000000_**
			up_assert: Assertion failed at file:armv7-m/up_hardfault.c line: 148 task: init
			up_registerdump: R0: 00000000 00000001 0d0cf610 00000003 0d0d2596 0d0d272a 0d0cf60f 0d09e484
			<...many more stack dump messages...>
	**Test3: Run Mic Model - Replace 3-folders, C++ Library** 
		Delete 3-folders in destination folder.
		Copy CC 3-folders to destination folder
		Built OK with Warning
			`firmware.spk` is successfully created.
			make: warning:  Clock skew detected.  Your build may be incomplete.
		Flashed OK
		Run daemon locally:				`edge-impulse-run-impulse`
			SER] Started inferencing, press CTRL+C to stop...
			LSE
			Inferencing settings:
				Interval: 0.0625 ms.
				Frame size: 16000
				Sample length: 1000 ms.
				No. of classes: 4
			Starting inferencing, press 'b' to break
			Recording...
			Recording done
			**_up_hardfault: PANIC!!! Hard fault: 40000000_**
			up_assert: Assertion failed at file:armv7-m/up_hardfault.c line: 148 task: init
			up_registerdump: R0: 00000000 00000001 0d0cf610 00000003 0d0d2596 0d0d272a 0d0cf60f 0d09e484
			<...many more stack dump messages...>

	**Test4: Run Mic Model - Merge 3-folders, C++ Library** 
		Copy CC 3-folders to destination folder
		Select merge folders when prompted
		Built OK with Warning
			`firmware.spk` is successfully created.
			make: warning:  Clock skew detected.  Your build may be incomplete.
		Flashed OK
		Run daemon locally:				`edge-impulse-run-impulse`
			[SER] Started inferencing, press CTRL+C to stop...
			LSE
			Inferencing settings:
				Interval: 0.0625 ms.
				Frame size: 16000
				Sample length: 1000 ms.
				No. of classes: 4
			Starting inferencing, press 'b' to break
			Recording...
			Recording done
			**_up_hardfault: PANIC!!! Hard fault: 40000000_**
			up_assert: Assertion failed at file:armv7-m/up_hardfault.c line: 148 task: init
			up_registerdump: R0: 00000000 00000001 0d0cf610 00000003 0d0d2596 0d0d272a 0d0cf60f 0d09e484

**Comment by automatiek** [comment]
Hi, did you also install the DSP files? Here's a doc describing how to https://developer.sony.com/develop/spresense/docs/arduino_tutorials_en.html#_install_dsp_files

**Comment by DeveloperMarcial** [comment]
The full error is:

```
$ edge-impulse-run-impulse --continuous
Edge Impulse impulse runner v1.16.3
[SER] Connecting to /dev/ttyUSB1
[SER] Serial is connected, trying to read config...
[SER] Retrieved configuration
[SER] Device is running AT command version 1.7.0
[SER] Started inferencing, press CTRL+C to stop...
NT
Inferencing settings:
	Interval: 0.062500ms.
	Frame size: 16000
	Sample length: 1000 ms.
	No. of classes: 4
Starting inferencing, press 'b' to break
up_hardfault: PANIC!!! Hard fault: 40000000
up_assert: Assertion failed at file:armv7-m/up_hardfault.c line: 148 task: init
up_registerdump: R0: 0d09fc74 00000001 0d0c9680 00000003 0d0cc606 0d0cc79a 0d0c967f 0d06f994
up_registerdump: R8: 0d06f994 00000065 0d09fc78 0d08d7d0 00000003 0d09fbe8 0d0101c1 0d010250
up_registerdump: xPSR: 01000000 BASEPRI: 000000e0 CONTROL: 00000000
up_registerdump: EXC_RETURN: ffffffe9
up_dumpstate: sp:     0d090aa8
up_dumpstate: IRQ stack:
up_dumpstate:   base: 0d090b00
up_dumpstate:   size: 00000800
up_dumpstate:   used: 00000150
up_stackdump: 0d090aa0: 00001fec 0d0376c7 000000e0 00000000 0d08d7d0 00000003 0d09fbe8 0d0101c1
up_stackdump: 0d090ac0: 0d010250 0d090ad0 0d037a17 00000000 0d08d7d0 0d037a1f 0d0379fd 0d0441bf
up_stackdump: 0d090ae0: 000000e0 0d041555 000000e0 0d09fb14 0d0cc79a 0d0c967f 0d06f994 0d03797b
up_dumpstate: sp:     0d09fbe8
up_dumpstate: User stack:
up_dumpstate:   base: 0d0a0248
up_dumpstate:   size: 00001fec
up_dumpstate:   used: 00000a20
up_stackdump: 0d09fbe0: 20000010 0d08d794 00000001 00000066 00000004 00000066 00000001 00000001
up_stackdump: 0d09fc00: 00000066 00000003 00000004 0d0cc606 0d0c9540 0d0c9680 ffffff80 ffffff80
up_stackdump: 0d09fc20: 0d09fc84 0d06f9a4 0d06f990 0d06f994 00000066 0d016e39 00000001 00000066
up_stackdump: 0d09fc40: 0d0d137c e0000000 41604ede 0d016e9f 41604ede 00000000 41900000 00000000
up_stackdump: 0d09fc60: 41700000 00010002 00010002 00000001 00000001 00000002 00000000 00000000
up_stackdump: 0d09fc80: 00000000 00000000 00000001 00000001 ffffff80 0000007f 0d0d13ac 0d08d1d4
up_stackdump: 0d09fca0: 00000004 00000001 00000006 00000002 00000033 3f4d10a4 00000004 00000001
up_stackdump: 0d09fcc0: 00000007 00000003 00000033 0d00d087 0d08c8d4 0d08c914 0d08d1d4 0d0d13ac
up_stackdump: 0d09fce0: 00000080 00000001 00000001 00000004 00000002 00000000 00000000 0d08d7d0
up_stackdump: 0d09fd00: 0d08dc84 00000009 0d08d788 0d08d5d8 0d08d5e4 0d08b9d4 0d09ff84 00000000
up_stackdump: 0d09fd20: 00000000 00000000 00000000 00000000 00000000 0d08dca8 0d070340 0d08d258
up_stackdump: 0d09fd40: 0d08d7d0 0d08dd38 00000000 0d08b9d4 0d09ff84 0d00acbf 0d09ff98 0d09febc
up_stackdump: 0d09fd60: 0053a751 00000000 0d08d214 0d003471 00000000 00000000 00000000 00000000
up_stackdump: 0d09fd80: 00000000 0d09fe4c 0d09febc 00000f78 0d09ff98 00000000 00000000 0d08b9d4
up_stackdump: 0d09fda0: 0d09ff84 0d0042c9 0d08d214 00000063 0d09fdf8 00000000 0d09ff98 00000000
up_stackdump: 0d09fdc0: 0d002f85 00000000 0053a751 00000000 00000063 0d09fdf8 0d08d214 0d08b9d4
up_stackdump: 0d09fde0: 0d09febc ffad3b0f 00000000 0d09ff98 0d0064b1 00000f78 0d08b818 0d00438b
up_stackdump: 0d09fe00: 0d09febc 0d004729 0d07c024 0d08b82c 00000001 00000000 00000000 0d09ff98
up_stackdump: 0d09fe20: 00000000 0052c4f1 00000000 00000001 0d037c46 00000019 00000028 0d0c12a0
up_stackdump: 0d09fe40: 00000001 00000f78 00000000 0d0c55a0 00000001 00000f78 0d09fe01 0d09ff30
up_stackdump: 0d09fe60: 000000e0 00000000 0d00af6d 0d09ff5c 0d085804 0d08b004 0d08df24 0d002f15
up_stackdump: 0d09fe80: ffffffff 00000000 00000000 0d09ff84 0d09ff98 00000000 00000001 0d002f15
up_stackdump: 0d09fea0: 0d002f27 0d002f15 ffffffff 0d004cb1 00000001 00000000 00000000 00023812
up_stackdump: 0d09fec0: 0d05c978 0d05c98c 0000000d 00000f78 00003e80 00000001 00003e80 00000000
up_stackdump: 0d09fee0: 00000000 00000000 3d800000 00000004 467a0000 00000001 0d07c010 00000000
up_stackdump: 0d09ff00: 00000000 000000ff 00000004 00000000 00000000 00000000 00000109 3b69e9ea
up_stackdump: 0d09ff20: c3000000 00000109 3b800000 c3000000 00000002 00000101 00000001 0d05c9a0
up_stackdump: 0d09ff40: 00000fa0 00000004 0d00ac85 0d00ac91 0d00aa15 0d00aca1 0d00ace1 0d07c000
up_stackdump: 0d09ff60: 0d08f000 0d09ff84 0d09ff98 0d00b0f1 0d00b0f1 0d004d71 0d098480 00000000
up_stackdump: 0d09ff80: 0d045181 0d00b0f1 0d032857 0d002f27 0d002f15 00000fa0 00000000 00000000
up_stackdump: 0d09ffa0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
up_stackdump: 0d09ffc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
up_stackdump: 0d09ffe0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
up_stackdump: 0d0a0000: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
up_stackdump: 0d0a0020: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
up_stackdump: 0d0a0040: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
up_stackdump: 0d0a0060: 00000000 00000000 00000000 00000000 00000000 00000039 00000000 00000000
up_stackdump: 0d0a0080: 0000e260 00000000 00000000 00000000 00000000 00000000 0d00b0f1 0d032857
up_stackdump: 0d0a00a0: 0d092a68 0d03edb1 0d0984e0 0d097d20 00000001 0d004e39 0d08b394 00000020
up_stackdump: 0d0a00c0: 0d0984e0 00000000 0d0984e0 0d004e41 0d001fbc 0d001f51 0d092a68 0d03edb1
up_stackdump: 0d0a00e0: 0d0984e0 0d097d20 0d092a68 0d03e9e9 0d097d38 0d032693 0d097d38 0d00a2b1
up_stackdump: 0d0a0100: 0d097d38 0d098481 0d0a0140 0d05c8c8 0d08b830 0d000000 0d07bc8c 00000000
up_stackdump: 0d0a0120: 00000000 00000000 00000000 0d00a74f 00000000 00000000 00000000 0d000000
up_stackdump: 0d0a0140: 0d097e10 00000011 00000011 00000000 00000000 00000000 00000000 00000000
up_stackdump: 0d0a0160: 00000000 00000000 00000000 0d097e20 041ac018 00000196 00000000 0d009707
up_stackdump: 0d0a0180: 0d000320 61000000 00000000 40240000 00000000 00000000 00000000 00000000
up_stackdump: 0d0a01a0: 00000000 00000000 00000000 00000000 00000000 00000000 0d05c8c8 0d08b830
up_stackdump: 0d0a01c0: 0d000000 0d07bc8c 00000000 0d00970f 041ac000 0d002e37 041ac000 0d07bc8c
up_stackdump: 0d0a01e0: 0d07bc6c 0d0002cf 00000058 000000bb 0000006b 00000000 bb589488 0000006b
up_stackdump: 0d0a0200: 00000000 00000000 393a3838 38353a34 3a42423a 00004236 00000000 00000000
up_stackdump: 0d0a0220: 00000000 00000000 00000000 00000101 00000000 00000000 00000000 0d03abb3
up_stackdump: 0d0a0240: 00000000 00000000 deadbeef 0d0a0254 00000000 74696e69 deadbe00 698a7b10
up_taskdump: Idle Task: PID=0 Stack Used=0 of 0
up_taskdump: hpwork: PID=1 Stack Used=576 of 2028
up_taskdump: lpwork: PID=2 Stack Used=352 of 2028
up_taskdump: lpwork: PID=3 Stack Used=352 of 2028
up_taskdump: lpwork: PID=4 Stack Used=352 of 2028
up_taskdump: cxd56_pm_task: PID=6 Stack Used=352 of 996
up_taskdump: <pthread>: PID=7 Stack Used=312 of 1020
up_taskdump: init: PID=8 Stack Used=2592 of 8172
up_taskdump: audio_manager: PID=9 Stack Used=704 of 2044
up_taskdump: media_player0: PID=10 Stack Used=344 of 3068
up_taskdump: media_player1: PID=11 Stack Used=344 of 3068
up_taskdump: out_mixer: PID=12 Stack Used=336 of 3068
up_taskdump: renderer0: PID=13 Stack Used=336 of 2044
up_taskdump: renderer1: PID=14 Stack Used=336 of 2044
up_taskdump: front_end: PID=15 Stack Used=576 of 2044
up_taskdump: media_recorder: PID=16 Stack Used=1112 of 2044
up_taskdump: capture0: PID=17 Stack Used=504 of 2044
up_taskdump: SRC: PID=18 Stack Used=344 of 2044

```

**Comment by automatiek** [comment]
Ok, thanks. I'll investigate.

**Comment by automatiek** [comment]
Closing per request. Tested on int8 and float with audio model both passed
