### ISSUE TITLE
run_nn_continuous() does not bring predictions forward

### ISSUE THREAD

**Issue by DeveloperMarcial** [edgeimpulse/firmware-sony-spresense#6]
Using: Edge Impulse Studio deployed Arduino Microphone Model Library
* This works as desired: `run_nn(true, 2000, use_max_baudrate);`
* Running this `run_nn_continuous(false);` results in Predictions = 0.00000 for all audio classes.
* Running this `run_nn_continuous(true);` results in Predictions = _<a_non_zero_value>_ for all audio classes printed due to the `true argument` and printed from `process_impulse_continuous()`. However, the Predictions printed in `run_nn_continuous()` are still 0.00000.

I suspect the sliding Window is not being implemented correctly.

**Comment by DeveloperMarcial** [comment]
The problem is `label_detected` is always `-1` or `EI_PC_RET_NO_EVENT_DETECTED`. Note that `label_detected` is the index of the `score` or `prediction` with the highest value.

I am not sure what the contents of `if (avg_scores->should_boost())` is trying to do but with `label_detected=EI_PC_RET_NO_EVENT_DETECTED` it is zeroing out all values in `result->classification[]`. *(It would be nice to have some more coder like comments in the source code.)*

So what indeed is the contents of `if (avg_scores->should_boost())` trying to do?

My fix was to rem out `if (avg_scores->should_boost())` such as:

```
#if EI_CLASSIFIER_CALIBRATION_ENABLED
        if (impulse->sensor == EI_CLASSIFIER_SENSOR_MICROPHONE) {
            if((void *)avg_scores != NULL && enable_maf == true) {
                if (enable_maf && !ei_calibration.is_configured) {
                    // perfcal is not configured, print msg first time
                    static bool has_printed_msg = false;

                    if (!has_printed_msg) {
                        ei_printf("WARN: run_classifier_continuous, enable_maf is true, but performance calibration is not configured.\n");
                        ei_printf("       Previously we'd run a moving-average filter over your outputs in this case, but this is now disabled.\n");
                        ei_printf("       Go to 'Performance calibration' in your Edge Impulse project to configure post-processing parameters.\n");
                        ei_printf("       (You can enable this from 'Dashboard' if it's not visible in your project)\n");
                        ei_printf("\n");

                        has_printed_msg = true;
                    }
                }
                else {
                    // perfcal is configured
                    int label_detected = avg_scores->trigger(result->classification);
/* ****************************************************************************************************************
                    if (avg_scores->should_boost())
                    {
                        for (int i = 0; i < impulse->label_count; i++) {
                            if (i == label_detected) {
                                result->classification[i].value = 1.0f;
                            }
                            else {
                                result->classification[i].value = 0.0f;
                            }
                        }
                    }
   **************************************************************************************************************** */
                }
            }
        }
#endif
```

**Comment by DeveloperMarcial** [comment]
**What is the contents of `if (avg_scores->should_boost())` Doing**

So this existing code
```
if (avg_scores->should_boost())
{
	for (int i = 0; i < impulse->label_count; i++)
	{
		if (i == label_detected)
                {
			result->classification[i].value = 1.0f;
		}
		else
		{
			result->classification[i].value = 0.0f;
		}
	}
}
```
is making the display of the Predictions easier to view. For example, if your Model is trained to classify keywords "yes" and "no", the typical example EI code shows:
```
         no:	0.06198
      noise:	0.90505
    unknown:	0.00238
        yes:	0.03057
```
The "boost()" feature makes the output look like:
```
	no:	0.00000
      noise:	1.00000
    unknown:	0.00000
        yes:	0.00000
```        
(NOTE: A more accurate name would be buck_boost(). The highest score gets boosted to unity and all others get bucked to zero.)

**The Fix**

So to make the code work as is, aka keeping the "boost()" feature one needs to align the `suppression` variables in file `ei_performance_calibration.h` with the `print_results` variable in file `ei_run_classifier.cpp`. In my case, to make this alignment *(I am not sure this is a universal fix)* happen the following changes are needed.

* When the class RecognizeEvents is instantiated:
  * `this->_suppression_count = this->_suppression_samples;`
becomes
  * `this->_suppression_count = -1;`

This allows the "boost()"   feature to execute and then in `ei_run_impulse.cpp` the `if statement` using variable `print_results` is satisfied and the Predictions are printed with the "boosted" values.
* In `ei_run_impulse.cpp`
  * `if (++print_results >= (EI_CLASSIFIER_SLICES_PER_MODEL_WINDOW >> 1)) {`
becomes
  * `if (++print_results >= (EI_CLASSIFIER_SLICES_PER_MODEL_WINDOW)+2) {`
and perhaps more globally maybe this is
  * `if (++print_results >= (EI_CLASSIFIER_SLICES_PER_MODEL_WINDOW)+(EI_CLASSIFIER_SLICES_PER_MODEL_WINDOW/2)) {`

This is aligns the `if (++print_results...` with `this->_suppression_samples`. Note that `_suppression_samples` starts counting from 0.
  
What this does is when `this->_suppression_samples=this->_suppression_count` then the next time we are in `ei_run_impulse.cpp` it will print the Predictions. If these 2 are out of sync then you'll see all zeros
```
	no:	0.00000
      noise:	0.00000
    unknown:	0.00000
        yes:	0.00000
```
because the code at the top of this post is setting all Predictions to zero, via `result->classification[i].value = 0.0f;`

---

I do not know enuf about the overall code but an alternate fix is to add an `if statement`
```
if (label_detected<0)
{
	// Don't boost.
}
```

As in:

```
// perfcal is configured
int label_detected = avg_scores->trigger(result->classification);

if (label_detected<0)
{
   // Don't boost.
}
else
{
   if (avg_scores->should_boost())
   {
      for (int i = 0; i < impulse->label_count; i++)
      {
         if (i == label_detected)
         {
            result->classification[i].value = 1.0f;
            }
            else
            {
               result->classification[i].value = 0.0f;
            }
         }
      }
   }
```
---

My general intuition says `const ei_model_performance_calibration_t ei_calibration` needs to be brought into file `ei_run_impulse.cpp` and the line `if (++print_results >= (EI_CLASSIFIER_SLICES_PER_MODEL_WINDOW >> 1)) {` changed accordingly.

**Comment by automatiek** [comment]
Hi @DeveloperMarcial, I understand the confusion with the new output for continuous inference. By adding performance calibration we can now do meaningful post-processing on device. But having a continuous stream of classification results wouldn't tell if a label is correctly classified, and the `0` or `1` notation does. 
I agree we should be more explicit on the type of output and we will improve on that end.

Thanks for the feedback!

Furthermore, we will disable the issue tracker on public repositories on Github. Having so many of them, makes it a hard to track the issues. Best to post issues on our forum. Thanks!
