### ISSUE TITLE
Cut-n-Paste Error: Sony camera can't resize smaller then 96x64 

### ISSUE THREAD

**Issue by DeveloperMarcial** [edgeimpulse/firmware-sony-spresense#7]
FILE: **ei_run_impulse.cpp**
LINE: **294 to 295**

`/* Sony camera can't resize smaller then 96x64 */`
`if(EI_CLASSIFIER_INPUT_WIDTH < 96 || EI_CLASSIFIER_INPUT_WIDTH < 64) {`

should be 

`/* Sony camera can't resize smaller then 96x64 */`
`if(EI_CLASSIFIER_INPUT_WIDTH < 96 || EI_CLASSIFIER_INPUT_HEIGHT< 64) {`

**Comment by automatiek** [comment]
Thanks @DeveloperMarcial,

This will be fixed in next release.
